Add support for publishing a project to a SQL Server (#33)
This adds the possibility to run `dotnet publish` on a project that uses `MSBuild.Sdk.SqlProj` in order to deploy the database to a local SQL Server instance.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -23,9 +23,13 @@ jobs:
     - uses: actions/checkout@v2
       with:
         fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
-    - uses: actions/setup-dotnet@v1
+
+    # Install .NET Core SDK
+    # TOOO: Remove this workaround once https://github.com/actions/setup-dotnet/issues/25 gets fixed
+    - name: Setup .NET Core
+      uses: coderpatros/setup-dotnet@sxs
       with:
-        dotnet-version: '3.1.102'
+        dotnet-version: 2.1.808,3.1.302
 
     # Install Nerdbank.GitVersioning
     - name: install nbgv
@@ -36,15 +40,15 @@ jobs:
       run: ./nbgv cloud -p ./src/MSBuild.Sdk.SqlProj/ --all-vars
 
     # Build command line tool
-    - name: dotnet build
-      run: dotnet build ./src/BuildDacpac/BuildDacpac.csproj -c Release
+    - name: dotnet build DacpacTool
+      run: dotnet build ./src/DacpacTool/DacpacTool.csproj -c Release
 
     # Run tests for command line tool
     - name: dotnet test
-      run: dotnet test ./test/BuildDacpac.Tests/BuildDacpac.Tests.csproj -c Release
+      run: dotnet test ./test/DacpacTool.Tests/DacpacTool.Tests.csproj -c Release
 
     # Run build for SDK package
-    - name: dotnet build
+    - name: dotnet build SDK
       run: dotnet build ./src/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj.csproj -c Release
 
     # Ensure that test project builds
@@ -80,7 +84,7 @@ jobs:
     strategy:
       matrix:
         os: [ "ubuntu-18.04", "macos-10.15", "windows-2019" ]
-        dotnet: [ '2.1.804', '2.2.207', '3.1.102' ]
+        dotnet: [ '2.1.808', '3.1.302' ]
       fail-fast: false
 
     steps:
@@ -138,8 +142,8 @@ jobs:
         name: binary-log-${{ matrix.os }}-${{ matrix.dotnet }}
         path: ./msbuild.binlog
 
-  # Attempt to deploy the resulting dacpac's to a SQL Server instance running in a container
-  deploy:
+  # Attempt to deploy the resulting dacpac's to a SQL Server instance running in a container using SqlPackage.exe
+  deploy-sqlpackage:
     runs-on: ubuntu-18.04
     needs: test
     services:
@@ -150,6 +154,12 @@ jobs:
           SA_PASSWORD: JdMsKZPBBA8kVFXVrj8d
         ports:
           - 1433:1433
+        options: >-
+          --health-cmd "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'JdMsKZPBBA8kVFXVrj8d' -Q 'SELECT 1' || exit 1"
+          --health-interval 10s
+          --health-timeout 3s
+          --health-retries 10
+          --health-start-period 10s
     steps:
     # Download artifacts
     - name: download-artifact
@@ -182,16 +192,85 @@ jobs:
       if: failure()
       uses: jwalton/gh-docker-logs@v1
 
+  # Attempt to deploy a project to a SQL Server instance running in a container using dotnet publish
+  deploy-publish:
+    runs-on: ubuntu-18.04
+    needs: test
+    services:
+      sqlserver:
+        image: mcr.microsoft.com/mssql/server:2019-latest
+        env:
+          ACCEPT_EULA: Y
+          SA_PASSWORD: JdMsKZPBBA8kVFXVrj8d
+        ports:
+          - 1433:1433
+        options: >-
+          --health-cmd "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'JdMsKZPBBA8kVFXVrj8d' -Q 'SELECT 1' || exit 1"
+          --health-interval 10s
+          --health-timeout 3s
+          --health-retries 10
+          --health-start-period 10s
+    steps:
+    # Fetch sources
+    - uses: actions/checkout@v2
+      with:
+        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
+
+    # Download artifact
+    - name: download-artifact
+      uses: actions/download-artifact@v1
+      with:
+        name: nuget-packages
+        path: test/TestProjectWithSDKRef/nuget-packages
+ 
+    # Setup .NET SDK
+    - uses: actions/setup-dotnet@v1
+      with:
+        dotnet-version: '3.1.302'
+
+    # Install Nerdbank.GitVersioning
+    - name: install nbgv
+      run: dotnet tool install --tool-path . nbgv
+
+    # Set version
+    - name: set version
+      run: ./nbgv cloud -p ./src/MSBuild.Sdk.SqlProj/ --all-vars
+      id: nbgv
+
+    # Replace tokens 
+    - uses: cschleiden/replace-tokens@v1
+      name: replace tokens
+      with:
+        files: 'test/TestProjectWithSDKRef/TestProjectWithSDKRef.csproj'
+
+    # Publish the project
+    - name: publish project
+      run: dotnet publish ./test/TestProjectWithSDKRef/TestProjectWithSDKRef.csproj /p:TargetUser=sa /p:TargetPassword=JdMsKZPBBA8kVFXVrj8d /bl
+
+    # Upload binary log
+    - name: upload
+      uses: actions/upload-artifact@v1
+      with:
+        name: binary-log-publish
+        path: ./msbuild.binlog
+
+    # Dump logs of the container if something failed
+    - name: Dump docker logs on failure
+      if: failure()
+      uses: jwalton/gh-docker-logs@v1
+
   # Publish the NuGet package to NuGet.org when building master branch
   publish:
     runs-on: ubuntu-18.04
     if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')
-    needs: deploy
+    needs:
+    - deploy-sqlpackage
+    - deploy-publish
     steps:
     # Setup .NET SDK
     - uses: actions/setup-dotnet@v1
       with:
-        dotnet-version: '3.1.102'
+        dotnet-version: '3.1.302'
 
     # Download artifacts
     - name: download-artifact
