Add verify step to other deploy jobs as well
Signed-off-by: Jonathan Mezach <jonathan.mezach@rr-wfm.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -259,6 +259,16 @@ jobs:
         /TargetDatabaseName:TestProjectWithSDKRef
         /TargetEncryptConnection:False
 
+    # Verify deployment
+    - name: verify-deployment
+      run: |
+        echo "Verifying deployment..."
+        if docker exec sqlserver /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "${{ secrets.SQL_SA_PASSWORD }}" -b -Q "SELECT 1 FROM dbo.TestTable;"; then
+          echo "Deployment succeeded!"
+        else
+          echo "Deployment failed!" >&2
+          exit 1
+
     # Dump logs of the container if something failed
     - name: Dump docker logs on failure
       if: failure()
@@ -340,9 +350,21 @@ jobs:
     - name: publish project
       run: dotnet publish ./test/TestProjectWithSDKRef/TestProjectWithSDKRef.csproj /p:TargetUser=sa /p:TargetPassword=${{ secrets.SQL_SA_PASSWORD }} /bl /p:DependencyVersion="2.*-*" /warnaserror:SQL71502
 
+    # Verify deployment
+    - name: verify-deployment
+      run: |
+        echo "Verifying deployment..."
+        if docker exec sqlserver /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "${{ secrets.SQL_SA_PASSWORD }}" -b -Q "SELECT 1 FROM dbo.TestTable;"; then
+          echo "Deployment succeeded!"
+        else
+          echo "Deployment failed!" >&2
+          exit 1
+        fi
+
     # Upload binary log
     - name: upload
       uses: actions/upload-artifact@v6
+      if: failure()
       with:
         name: binary-log-publish
         path: ./msbuild.binlog
@@ -423,7 +445,7 @@ jobs:
     - name: verify-deployment
       run: |
         echo "Verifying deployment..."
-        if docker exec sqlserver /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "${{ secrets.SQL_SA_PASSWORD }}" -b -Q "SELECT 1 FROM dbo.TestTable;" > /dev/null 2>&1; then
+        if docker exec sqlserver /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "${{ secrets.SQL_SA_PASSWORD }}" -b -Q "SELECT 1 FROM dbo.TestTable;"; then
           echo "Deployment succeeded!"
         else
           echo "Deployment failed!" >&2
